import type {
  Automation,
  Integration,
  AILog,
  DashboardMetrics,
  Finding,
} from "@/types";

export const mockMetrics: DashboardMetrics = {
  total_automations: 12,
  active_automations: 8,
  total_time_saved: 147,
  time_saved_this_week: 23,
  total_runs: 1284,
  success_rate: 97.3,
  connected_integrations: 6,
  ai_score: 82,
  trend_automations: 15,
  trend_time_saved: 24,
};

export const mockAutomations: Automation[] = [
  {
    id: "1",
    org_id: "org_1",
    name: "Tri automatique des emails clients",
    description:
      "Analyse chaque email entrant, le categorise (support, vente, admin) et le redirige vers le bon canal Slack avec un resume IA.",
    status: "active",
    trigger: "Nouvel email recu sur contact@",
    actions: [
      { type: "gmail_read", config: {}, order: 1 },
      { type: "ai_classify", config: {}, order: 2 },
      { type: "slack_send", config: {}, order: 3 },
    ],
    time_saved_hours: 18,
    runs_count: 342,
    success_rate: 98.5,
    created_by: "ai",
    last_run_at: "2026-04-04T09:15:00Z",
    created_at: "2026-03-15T10:00:00Z",
  },
  {
    id: "2",
    org_id: "org_1",
    name: "Generation de rapports hebdomadaires",
    description:
      "Compile les donnees de vente, support et operations chaque lundi matin. Genere un PDF et l'envoie sur Slack + email direction.",
    status: "active",
    trigger: "Chaque lundi a 7h00",
    actions: [
      { type: "sheets_read", config: {}, order: 1 },
      { type: "ai_summarize", config: {}, order: 2 },
      { type: "pdf_generate", config: {}, order: 3 },
      { type: "slack_send", config: {}, order: 4 },
    ],
    time_saved_hours: 32,
    runs_count: 14,
    success_rate: 100,
    created_by: "ai",
    last_run_at: "2026-03-31T07:00:00Z",
    created_at: "2026-03-10T14:00:00Z",
  },
  {
    id: "3",
    org_id: "org_1",
    name: "Onboarding nouveau client",
    description:
      "Quand un deal est gagne dans le CRM, cree automatiquement le dossier Drive, le canal Slack, le projet Notion et envoie le kit de bienvenue.",
    status: "active",
    trigger: "Deal marque 'Gagne' dans HubSpot",
    actions: [
      { type: "drive_create_folder", config: {}, order: 1 },
      { type: "slack_create_channel", config: {}, order: 2 },
      { type: "notion_create_page", config: {}, order: 3 },
      { type: "gmail_send", config: {}, order: 4 },
    ],
    time_saved_hours: 24,
    runs_count: 8,
    success_rate: 100,
    created_by: "user",
    last_run_at: "2026-04-02T16:30:00Z",
    created_at: "2026-03-20T09:00:00Z",
  },
  {
    id: "4",
    org_id: "org_1",
    name: "Suivi des factures impayees",
    description:
      "Detecte les factures en retard de plus de 7 jours, envoie un rappel automatique au client et notifie le responsable comptable.",
    status: "active",
    trigger: "Chaque jour a 9h00",
    actions: [
      { type: "stripe_check", config: {}, order: 1 },
      { type: "gmail_send", config: {}, order: 2 },
      { type: "slack_notify", config: {}, order: 3 },
    ],
    time_saved_hours: 12,
    runs_count: 89,
    success_rate: 95.5,
    created_by: "ai",
    last_run_at: "2026-04-04T09:00:00Z",
    created_at: "2026-03-12T11:00:00Z",
  },
  {
    id: "5",
    org_id: "org_1",
    name: "Veille concurrentielle automatisee",
    description:
      "Surveille les sites et reseaux sociaux des 5 principaux concurrents. Genere un rapport de veille chaque semaine avec les changements detectes.",
    status: "suggested",
    trigger: "Chaque vendredi a 18h00",
    actions: [
      { type: "web_scrape", config: {}, order: 1 },
      { type: "ai_analyze", config: {}, order: 2 },
      { type: "notion_update", config: {}, order: 3 },
    ],
    time_saved_hours: 0,
    runs_count: 0,
    success_rate: 0,
    created_by: "ai",
    last_run_at: null,
    created_at: "2026-04-03T14:00:00Z",
  },
  {
    id: "6",
    org_id: "org_1",
    name: "Synchronisation CRM — Comptabilite",
    description:
      "Synchronise les contacts et montants entre HubSpot et le logiciel de comptabilite. Detecte les incoherences et alerte.",
    status: "paused",
    trigger: "Toutes les 6 heures",
    actions: [
      { type: "hubspot_read", config: {}, order: 1 },
      { type: "accounting_sync", config: {}, order: 2 },
      { type: "slack_alert", config: {}, order: 3 },
    ],
    time_saved_hours: 8,
    runs_count: 156,
    success_rate: 92.3,
    created_by: "user",
    last_run_at: "2026-03-28T18:00:00Z",
    created_at: "2026-03-08T08:00:00Z",
  },
];

export const mockIntegrations: Integration[] = [
  {
    id: "1",
    org_id: "org_1",
    type: "google_workspace",
    name: "Google Workspace",
    status: "connected",
    icon: "G",
    last_sync_at: "2026-04-04T10:00:00Z",
    config: {},
    created_at: "2026-03-10T10:00:00Z",
  },
  {
    id: "2",
    org_id: "org_1",
    type: "slack",
    name: "Slack",
    status: "connected",
    icon: "S",
    last_sync_at: "2026-04-04T09:45:00Z",
    config: {},
    created_at: "2026-03-10T10:00:00Z",
  },
  {
    id: "3",
    org_id: "org_1",
    type: "notion",
    name: "Notion",
    status: "connected",
    icon: "N",
    last_sync_at: "2026-04-04T08:30:00Z",
    config: {},
    created_at: "2026-03-11T10:00:00Z",
  },
  {
    id: "4",
    org_id: "org_1",
    type: "hubspot",
    name: "HubSpot",
    status: "connected",
    icon: "H",
    last_sync_at: "2026-04-04T07:00:00Z",
    config: {},
    created_at: "2026-03-12T10:00:00Z",
  },
  {
    id: "5",
    org_id: "org_1",
    type: "stripe_integration",
    name: "Stripe",
    status: "connected",
    icon: "$",
    last_sync_at: "2026-04-04T09:00:00Z",
    config: {},
    created_at: "2026-03-10T10:00:00Z",
  },
  {
    id: "6",
    org_id: "org_1",
    type: "make",
    name: "Make (Integromat)",
    status: "connected",
    icon: "M",
    last_sync_at: "2026-04-03T22:00:00Z",
    config: {},
    created_at: "2026-03-10T10:00:00Z",
  },
  {
    id: "7",
    org_id: "org_1",
    type: "calendar",
    name: "Google Calendar",
    status: "disconnected",
    icon: "C",
    last_sync_at: null,
    config: {},
    created_at: "2026-03-10T10:00:00Z",
  },
  {
    id: "8",
    org_id: "org_1",
    type: "trello",
    name: "Trello",
    status: "disconnected",
    icon: "T",
    last_sync_at: null,
    config: {},
    created_at: "2026-03-10T10:00:00Z",
  },
  {
    id: "9",
    org_id: "org_1",
    type: "airtable",
    name: "Airtable",
    status: "disconnected",
    icon: "A",
    last_sync_at: null,
    config: {},
    created_at: "2026-03-10T10:00:00Z",
  },
  {
    id: "10",
    org_id: "org_1",
    type: "salesforce",
    name: "Salesforce",
    status: "disconnected",
    icon: "SF",
    last_sync_at: null,
    config: {},
    created_at: "2026-03-10T10:00:00Z",
  },
];

export const mockFindings: Finding[] = [
  {
    category: "Processus",
    title: "3 taches repetitives detectees dans la gestion RH",
    description:
      "L'analyse des flux Google Sheets et emails revele que la gestion des conges, les fiches de paie et les notes de frais suivent un pattern automatisable. Temps recuperable estime : 6h/semaine.",
    severity: "high",
  },
  {
    category: "Communication",
    title: "37% des emails internes sont des relances",
    description:
      "Plus d'un tiers des emails entre equipes sont des relances sur des taches en attente. Un systeme de notifications Slack automatisees reduirait ce volume de 80%.",
    severity: "high",
  },
  {
    category: "Donnees",
    title: "Doublons detectes entre CRM et facturation",
    description:
      "12 contacts presentent des incoherences entre HubSpot et votre systeme de facturation. Une synchronisation automatique eliminerait ce risque.",
    severity: "medium",
  },
  {
    category: "Opportunite",
    title: "Reporting client automatisable",
    description:
      "Vos rapports clients mensuels suivent une structure identique. L'IA peut les generer automatiquement a partir des donnees Sheets + CRM.",
    severity: "medium",
  },
  {
    category: "Securite",
    title: "Acces Google Drive non audites depuis 90 jours",
    description:
      "Certains documents partages n'ont pas ete revus depuis plus de 3 mois. Recommandation : automatiser l'audit des permissions tous les 30 jours.",
    severity: "low",
  },
];

export const mockAILogs: AILog[] = [
  {
    id: "1",
    org_id: "org_1",
    action: "Analyse hebdomadaire completee",
    details:
      "5 recommandations generees, 2 automatisations suggerees, score global : 82/100",
    status: "success",
    created_at: "2026-04-04T06:00:00Z",
  },
  {
    id: "2",
    org_id: "org_1",
    action: "Automatisation creee : Tri emails",
    details:
      "Nouvelle automatisation deployee automatiquement suite a l'analyse des patterns d'emails entrants",
    status: "success",
    created_at: "2026-04-03T14:30:00Z",
  },
  {
    id: "3",
    org_id: "org_1",
    action: "Synchronisation HubSpot — Sheets",
    details: "342 contacts synchronises, 12 incoherences detectees",
    status: "info",
    created_at: "2026-04-03T09:00:00Z",
  },
  {
    id: "4",
    org_id: "org_1",
    action: "Erreur : connexion Trello expiree",
    details:
      "Le token d'acces Trello a expire. Reconnexion necessaire pour maintenir la synchronisation.",
    status: "error",
    created_at: "2026-04-02T16:00:00Z",
  },
  {
    id: "5",
    org_id: "org_1",
    action: "Optimisation : rapport hebdo accelere",
    details:
      "Le temps de generation du rapport hebdomadaire a ete reduit de 45s a 12s grace a la mise en cache des donnees.",
    status: "success",
    created_at: "2026-04-01T11:00:00Z",
  },
];

export const mockWeeklyData = [
  { label: "Lun", value: 4.2 },
  { label: "Mar", value: 3.8 },
  { label: "Mer", value: 5.1 },
  { label: "Jeu", value: 3.5 },
  { label: "Ven", value: 4.8 },
  { label: "Sam", value: 1.2 },
  { label: "Dim", value: 0.4 },
];

export const mockMonthlyData = [
  { label: "S1", value: 28 },
  { label: "S2", value: 35 },
  { label: "S3", value: 42 },
  { label: "S4", value: 42 },
];
